name: pre-release

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  pre_release:
    name: Pre Release
    runs-on: ubuntu-latest

    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create env file
        run: echo 'DATABASE_URL='$DATABASE_URL > ./.env
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres_db.ports[5432] }}/postgres

      - name: Cache crate
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo plugins
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-plugins

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install sqlx-cli
        run: which sqlx || cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: Setup database
        run: sqlx migrate run

      - name: Build
        run: cargo build --release

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: dev
          prerelease: true
          title: Development Build
          files: |
            target/release/market-api-server
