name: tagged-release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  tagged_release:
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache crate
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo plugins
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-plugins

      - name: Create env file
        run: echo 'DATABASE_URL=sqlite://./db.sqlite' > ./.env

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install sqlx-cli
        run: which sqlx || cargo install sqlx-cli --no-default-features --features sqlite

      - name: Setup database
        run: |
          sqlx database create
          sqlx migrate run

      - name: Build
        run: cargo build --release

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            target/release/market-api-server
