name: tagged-release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  tagged_release:
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create env file
        run: echo 'DATABASE_URL=sqlite://./db.sqlite' > ./.env

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install sqlx-cli
        uses: actions-rs/install@v0.1
        with:
          crate: sqlx-cli
          version: latest
          use-tool-cache: true

      - name: Setup database
        run: |
          sqlx database create
          sqlx migrate run

      - name: Build
        run: |
          cargo build --release

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            target/release/market-api-server
