name: test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create env file
        run: echo 'DATABASE_URL=sqlite://./db.sqlite' > ./.env

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install sqlx-cli
        uses: actions-rs/install@v0.1
        with:
          crate: sqlx-cli
          version: latest
          use-tool-cache: true

      - name: Setup database
        run: |
          sqlx database create
          sqlx migrate run

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  check_fmt:
    name: Check fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: fmt
        run: cargo fmt -- --check
